export type TSvgIcons =
	| 'CustomApple'
	| 'CustomFacebook'
	| 'CustomFactory'
	| 'CustomFrance'
	| 'CustomGermany'
	| 'CustomGoogle'
	| 'CustomGithub'
	| 'CustomHtml5'
	| 'CustomPayoneer'
	| 'CustomPaypal'
	| 'CustomReact'
	| 'CustomRocketLaunch'
	| 'CustomSaudiArabia'
	| 'CustomStorybook'
	| 'CustomSwift'
	| 'CustomTurkey'
	| 'CustomUsa';
